"""
One-shot seed script: writes all 12 industries into
IndustryList, IndustryMeta, IndustryNode, IndustryEdge, StockMeta.
Run once: python seed_industries.py
"""

import json
import sys
import os

sys.path.insert(0, os.path.dirname(__file__))

from datetime import datetime
from sqlalchemy.dialects.sqlite import insert as sqlite_insert
from db import (
    SessionLocal,
    engine,
    Base,
    IndustryList,
    IndustryMeta,
    IndustryNode,
    IndustryEdge,
    StockMeta,
)

Base.metadata.create_all(bind=engine)
db = SessionLocal()

NOW = datetime.utcnow()


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------
def upsert_list(row: dict):
    stmt = sqlite_insert(IndustryList).values(**row)
    stmt = stmt.on_conflict_do_update(
        index_elements=["industry_id"],
        set_={k: stmt.excluded[k] for k in row if k != "industry_id"},
    )
    db.execute(stmt)


def upsert_meta(row: dict):
    stmt = sqlite_insert(IndustryMeta).values(**row)
    stmt = stmt.on_conflict_do_update(
        index_elements=["industry_id"],
        set_={k: stmt.excluded[k] for k in row if k != "industry_id"},
    )
    db.execute(stmt)


def upsert_node(row: dict):
    stmt = sqlite_insert(IndustryNode).values(**row)
    stmt = stmt.on_conflict_do_update(
        index_elements=["industry_id", "node_id"],
        set_={k: stmt.excluded[k] for k in row if k not in ("industry_id", "node_id")},
    )
    db.execute(stmt)


def upsert_edge(row: dict):
    stmt = sqlite_insert(IndustryEdge).values(**row)
    stmt = stmt.on_conflict_do_update(
        index_elements=["industry_id", "edge_id"],
        set_={k: stmt.excluded[k] for k in row if k not in ("industry_id", "edge_id")},
    )
    db.execute(stmt)


def upsert_stock(code: str, name: str, market: str, industry_ids: list):
    stmt = sqlite_insert(StockMeta).values(
        code=code,
        name=name,
        market=market,
        industry_ids=json.dumps(industry_ids, ensure_ascii=False),
        updated_at=NOW,
    )
    stmt = stmt.on_conflict_do_update(
        index_elements=["code"],
        set_={
            "name": stmt.excluded.name,
            "market": stmt.excluded.market,
            "industry_ids": stmt.excluded.industry_ids,
            "updated_at": stmt.excluded.updated_at,
        },
    )
    db.execute(stmt)


# ---------------------------------------------------------------------------
# 0. overview
# ---------------------------------------------------------------------------
upsert_list(
    dict(
        industry_id="overview",
        name="AI算力产业链全景",
        sort_order=0,
        description="覆盖GPU/PCB/存储/光模块/液冷/供配电等全链路核心产业",
        icon="🌐",
        company_count=0,
        last_analyzed="2026-06-27",
        representatives=json.dumps(["英伟达", "AMD", "英特尔"]),
        updated_at=NOW,
    )
)
upsert_meta(
    dict(
        industry_id="overview",
        sort_order=0,
        title="AI算力产业链全景概览",
        subtitle="涵盖从芯片到IDC的完整AI算力供应链",
        layer_labels=json.dumps(["芯片层", "连接层", "散热/电源层", "系统集成层"]),
        updated_at=NOW,
    )
)
for nid, x, y, label, icon, desc, layer, ticker, market, stocks in [
    ("aigpu", 200, 0, "AI芯片", "🔲", "GPU/NPU算力芯片", "core", "NVDA", "US", []),
    (
        "pcb",
        500,
        0,
        "PCB",
        "📟",
        "印制电路板",
        "core",
        "002463",
        "A股",
        ["002463", "603228", "300316", "002916", "000100"],
    ),
    (
        "memory",
        800,
        0,
        "存储芯片",
        "💾",
        "HBM/DRAM/NAND",
        "core",
        "000709",
        "A股",
        ["000709", "688008", "688008"],
    ),
    (
        "optics",
        1100,
        0,
        "光模块",
        "🔦",
        "光模块与CPO",
        "core",
        "300308",
        "A股",
        ["300308", "002449", "688498", "300505"],
    ),
    (
        "fiber",
        1400,
        0,
        "光纤光缆",
        "🌀",
        "光纤光缆制造",
        "upstream",
        "600487",
        "A股",
        ["600487", "601869", "002878"],
    ),
    (
        "mlcc",
        350,
        210,
        "MLCC",
        "⚡",
        "积层陶瓷电容器",
        "upstream",
        "603585",
        "A股",
        ["603585", "300373"],
    ),
    (
        "liquidcool",
        650,
        210,
        "液冷散热",
        "❄️",
        "液冷散热解决方案",
        "downstream",
        "002463",
        "A股",
        ["002463", "600811", "300677", "688696"],
    ),
    (
        "aipower",
        950,
        210,
        "AI供配电",
        "⚡",
        "PSU/BBU/HVDC电源",
        "downstream",
        "300724",
        "A股",
        ["300724", "002407", "688395", "301157"],
    ),
    (
        "coppercable",
        1250,
        210,
        "高速铜缆",
        "🔌",
        "DAC/AEC高速铜连接",
        "downstream",
        "605268",
        "A股",
        ["605268", "300693"],
    ),
    (
        "idc",
        1550,
        210,
        "IDC运营",
        "🏢",
        "智算中心/IDC运营",
        "application",
        "300353",
        "A股",
        ["300353", "002308", "600775"],
    ),
    (
        "glasssub",
        650,
        420,
        "玻璃基板",
        "🔬",
        "半导体封装玻璃基板",
        "upstream",
        "600876",
        "A股",
        ["600876", "600707", "000012", "600586", "605305", "300408", "002006"],
    ),
]:
    upsert_node(
        dict(
            industry_id="overview",
            node_id=nid,
            x=x,
            y=y,
            label=label,
            icon=icon,
            desc=desc,
            layer=layer,
            ticker=ticker,
            market=market,
            stocks=json.dumps(stocks),
            updated_at=NOW,
        )
    )

for eid, src, tgt, lbl in [
    ("e-ov-gpu-pcb", "aigpu", "pcb", "承载"),
    ("e-ov-gpu-mem", "aigpu", "memory", "配套"),
    ("e-ov-gpu-opt", "aigpu", "optics", "互联"),
    ("e-ov-pcb-liq", "pcb", "liquidcool", "集成"),
    ("e-ov-pcb-idc", "pcb", "idc", "部署"),
    ("e-ov-opt-fiber", "optics", "fiber", "依赖"),
    ("e-ov-liq-idc", "liquidcool", "idc", "散热"),
    ("e-ov-pwr-idc", "aipower", "idc", "供电"),
    ("e-ov-cu-idc", "coppercable", "idc", "互联"),
    ("e-ov-glass-pcb", "glasssub", "pcb", "基板"),
]:
    upsert_edge(
        dict(
            industry_id="overview",
            edge_id=eid,
            source=src,
            target=tgt,
            layer="",
            label=lbl,
            updated_at=NOW,
        )
    )

# ---------------------------------------------------------------------------
# 1. aigpu
# ---------------------------------------------------------------------------
AIGPU_STOCKS = [
    ("688256", "寒武纪", "A股"),
    ("688041", "海光信息", "A股"),
    ("000977", "浪潮信息", "A股"),
    ("688099", "晶晨股份", "A股"),
    ("002409", "雅克科技", "A股"),
    ("688981", "中芯国际", "A股"),
    ("301269", "华大九天", "A股"),
    ("688521", "芯原股份", "A股"),
    ("600584", "长电科技", "A股"),
    ("300474", "景嘉微", "A股"),
    ("603019", "中科曙光", "A股"),
]
for code, name, mkt in AIGPU_STOCKS:
    upsert_stock(code, name, mkt, ["aigpu"])

upsert_list(
    dict(
        industry_id="aigpu",
        name="AI算力芯片（GPU/NPU）",
        sort_order=1,
        description="以英伟达GPU为核心、国产替代加速推进的AI算力芯片产业链图谱",
        icon="🔲",
        company_count=len(AIGPU_STOCKS),
        last_analyzed="2026-06-27",
        representatives=json.dumps(["海光信息", "寒武纪", "华大九天", "长电科技"]),
        updated_at=NOW,
    )
)
upsert_meta(
    dict(
        industry_id="aigpu",
        sort_order=1,
        title="AI算力芯片供应链",
        subtitle="以英伟达GPU为核心、国产替代加速推进的AI算力芯片产业链图谱",
        layer_labels=json.dumps(
            ["L0 EDA/制程/封装", "L1 核心算力芯片", "L2 AI算力系统", "L3 算力应用"]
        ),
        updated_at=NOW,
    )
)
for nid, x, y, label, icon, desc, layer, ticker, market, stocks, group in [
    (
        "cadence",
        150,
        0,
        "Cadence",
        "🛠",
        "EDA工具龙头",
        "upstream",
        "CDNS",
        "US",
        [],
        "EDA/IP",
    ),
    (
        "synopsys",
        500,
        0,
        "Synopsys",
        "🛠",
        "EDA/IP核供应商",
        "upstream",
        "SNPS",
        "US",
        [],
        "EDA/IP",
    ),
    (
        "arm",
        850,
        0,
        "ARM",
        "💡",
        "CPU/NPU IP授权",
        "upstream",
        "ARM",
        "US",
        [],
        "EDA/IP",
    ),
    (
        "huada",
        1200,
        0,
        "华大九天",
        "🛠",
        "国产EDA龙头",
        "upstream",
        "301269",
        "A股",
        ["301269"],
        "EDA/IP",
    ),
    (
        "yake",
        1550,
        0,
        "雅克科技",
        "⚗️",
        "半导体特种气体材料",
        "upstream",
        "002409",
        "A股",
        ["002409"],
        "EDA/IP",
    ),
    (
        "nvidia",
        200,
        210,
        "英伟达",
        "🔲",
        "GPU算力全球龙头",
        "core",
        "NVDA",
        "US",
        [],
        "算力芯片",
    ),
    (
        "amd",
        550,
        210,
        "AMD",
        "🔲",
        "GPU/CPU竞争者",
        "core",
        "AMD",
        "US",
        [],
        "算力芯片",
    ),
    (
        "haiguang",
        900,
        210,
        "海光信息",
        "🔲",
        "国产GPU/DCU芯片",
        "core",
        "688041",
        "A股",
        ["688041"],
        "算力芯片",
    ),
    (
        "cambricon",
        1250,
        210,
        "寒武纪",
        "🧠",
        "AI NPU芯片，云端推理",
        "core",
        "688256",
        "A股",
        ["688256"],
        "算力芯片",
    ),
    (
        "jingwei",
        1600,
        210,
        "景嘉微",
        "🔲",
        "国产GPU，军工+民用",
        "core",
        "300474",
        "A股",
        ["300474"],
        "算力芯片",
    ),
    (
        "tsmc",
        250,
        420,
        "台积电",
        "🏭",
        "3nm/5nm先进晶圆代工",
        "downstream",
        "TSM",
        "US",
        [],
        "晶圆制造",
    ),
    (
        "smic",
        600,
        420,
        "中芯国际",
        "🏭",
        "国内最先进晶圆代工",
        "downstream",
        "688981",
        "A股",
        ["688981"],
        "晶圆制造",
    ),
    (
        "xinyuan",
        950,
        420,
        "芯原股份",
        "🔬",
        "芯片设计平台IP",
        "downstream",
        "688521",
        "A股",
        ["688521"],
        "晶圆制造",
    ),
    (
        "changdian",
        1300,
        420,
        "长电科技",
        "📦",
        "封装测试，HBM/CoWoS",
        "downstream",
        "600584",
        "A股",
        ["600584"],
        "封装测试",
    ),
    (
        "inspur",
        400,
        630,
        "浪潮信息",
        "🖥",
        "AI服务器整机，英伟达DGX系",
        "application",
        "000977",
        "A股",
        ["000977"],
        "AI系统",
    ),
    (
        "sugon",
        800,
        630,
        "中科曙光",
        "🖥",
        "AI服务器/HPC系统",
        "application",
        "603019",
        "A股",
        ["603019"],
        "AI系统",
    ),
    (
        "jingchen",
        1200,
        630,
        "晶晨股份",
        "🔬",
        "AI边缘/终端NPU芯片",
        "application",
        "688099",
        "A股",
        ["688099"],
        "AI系统",
    ),
]:
    upsert_node(
        dict(
            industry_id="aigpu",
            node_id=nid,
            x=x,
            y=y,
            label=label,
            icon=icon,
            desc=desc,
            layer=layer,
            ticker=ticker,
            market=market,
            stocks=json.dumps(stocks),
            group_name=group,
            updated_at=NOW,
        )
    )

for eid, src, tgt, lbl in [
    ("e-gpu-cad-nv", "cadence", "nvidia", "EDA"),
    ("e-gpu-syn-nv", "synopsys", "nvidia", "EDA"),
    ("e-gpu-arm-cam", "arm", "cambricon", "IP核"),
    ("e-gpu-hd-hai", "huada", "haiguang", "国产EDA"),
    ("e-gpu-yake-tsmc", "yake", "tsmc", "特种气体"),
    ("e-gpu-nv-tsmc", "nvidia", "tsmc", "流片"),
    ("e-gpu-hai-smic", "haiguang", "smic", "流片"),
    ("e-gpu-cam-smic", "cambricon", "smic", "流片"),
    ("e-gpu-xy-tsmc", "xinyuan", "tsmc", "IP"),
    ("e-gpu-tsmc-cd", "tsmc", "changdian", "封装"),
    ("e-gpu-smic-cd", "smic", "changdian", "封装"),
    ("e-gpu-cd-ins", "changdian", "inspur", "芯片"),
    ("e-gpu-nv-ins", "nvidia", "inspur", "GPU供货"),
    ("e-gpu-hai-sg", "haiguang", "sugon", "DCU"),
    ("e-gpu-cam-jc", "cambricon", "jingchen", "NPU"),
]:
    upsert_edge(
        dict(
            industry_id="aigpu",
            edge_id=eid,
            source=src,
            target=tgt,
            layer="",
            label=lbl,
            updated_at=NOW,
        )
    )

# ---------------------------------------------------------------------------
# 2. pcb
# ---------------------------------------------------------------------------
PCB_STOCKS = [
    ("600176", "中国巨石", "A股"),
    ("601208", "东材科技", "A股"),
    ("688300", "联瑞新材", "A股"),
    ("000657", "中钨高新", "A股"),
    ("600183", "生益科技", "A股"),
    ("002436", "兴森科技", "A股"),
    ("002463", "沪电股份", "A股"),
    ("002916", "深南电路", "A股"),
    ("300476", "胜宏科技", "A股"),
    ("002938", "鹏鼎控股", "A股"),
    ("601138", "工业富联", "A股"),
    ("002475", "立讯精密", "A股"),
    ("603186", "华正新材", "A股"),
    ("688519", "南亚新材", "A股"),
    ("688183", "海光信息", "A股"),
    ("603256", "华铁应急", "A股"),
    ("002594", "广和通", "A股"),
    ("688082", "盛合晶微", "A股"),
    ("300476", "胜宏科技", "A股"),
    ("000063", "中兴通讯", "A股"),
    ("301377", "中熔电气", "A股"),
    ("302938", "鹏鼎控股", "A股"),
    ("601138", "工业富联", "A股"),
    ("002938", "鹏鼎控股", "A股"),
    ("002463", "沪电股份", "A股"),
]
PCB_STOCKS = list({code: (code, name, mkt) for code, name, mkt in PCB_STOCKS}.values())
for code, name, mkt in PCB_STOCKS:
    upsert_stock(code, name, mkt, ["pcb"])

upsert_list(
    dict(
        industry_id="pcb",
        name="PCB（印制电路板）",
        sort_order=2,
        description="覆盖覆铜板、高频高速PCB、ABF载板等全链路，AI服务器HDI板需求驱动",
        icon="📟",
        company_count=len(PCB_STOCKS),
        last_analyzed="2026-06-27",
        representatives=json.dumps(["深南电路", "沪电股份", "生益科技", "鹏鼎控股"]),
        updated_at=NOW,
    )
)
upsert_meta(
    dict(
        industry_id="pcb",
        sort_order=2,
        title="PCB 企业供应链",
        subtitle="以英伟达为核心的高端PCB产业企业关系图谱",
        layer_labels=json.dumps(
            [
                "L0 原材料企业",
                "L1 覆铜板/钻针企业",
                "L2 PCB制造企业",
                "L3 组装/测试企业",
                "L4 终端客户",
            ]
        ),
        updated_at=NOW,
    )
)
for nid, x, y, label, icon, desc, layer, ticker, market, stocks, group in [
    (
        "glass_fiber",
        150,
        0,
        "中国巨石",
        "🌀",
        "超薄电子布→ABF载板关键基材",
        "upstream",
        "600176",
        "A股",
        ["600176"],
        "原材料",
    ),
    (
        "silica",
        450,
        0,
        "联瑞新材",
        "⚗️",
        "球形硅微粉（低介电填料）→高频高速CCL",
        "upstream",
        "688300",
        "A股",
        ["688300"],
        "原材料",
    ),
    (
        "resin",
        750,
        0,
        "东材科技",
        "🧪",
        "高频高速覆铜板树脂/无卤材料",
        "upstream",
        "601208",
        "A股",
        ["601208"],
        "原材料",
    ),
    (
        "copper_foil",
        1050,
        0,
        "铜箔原料",
        "🔶",
        "电解铜箔/高端高速铜箔",
        "upstream",
        "",
        "",
        [],
        "原材料",
    ),
    (
        "drill_bit",
        1350,
        0,
        "中钨高新",
        "🔩",
        "PCB钻针核心材料（硬质合金），AI服务器HDI板钻孔耗材",
        "upstream",
        "000657",
        "A股",
        ["000657"],
        "钻针/耗材",
    ),
    (
        "ccl_shengyi",
        200,
        210,
        "生益科技",
        "📦",
        "CCL覆铜板龙头，M8/M9产品已获英伟达交换板认证",
        "core",
        "600183",
        "A股",
        ["600183"],
        "覆铜板",
    ),
    (
        "ccl_huazheng",
        500,
        210,
        "华正新材",
        "📦",
        "高速覆铜板/无卤材料",
        "core",
        "603186",
        "A股",
        ["603186"],
        "覆铜板",
    ),
    (
        "ccl_nanya",
        800,
        210,
        "南亚新材",
        "📦",
        "高频高速覆铜板，ABF前道材料",
        "core",
        "688519",
        "A股",
        ["688519"],
        "覆铜板",
    ),
    (
        "ccl_lianrui",
        1100,
        210,
        "兴森科技",
        "📟",
        "快样PCB/HDI板，AI服务器多层板",
        "core",
        "002436",
        "A股",
        ["002436"],
        "覆铜板",
    ),
    (
        "pcb_hudian",
        300,
        420,
        "沪电股份",
        "📟",
        "高速高频PCB龙头，服务器/通信主板",
        "core",
        "002463",
        "A股",
        ["002463"],
        "PCB制造",
    ),
    (
        "pcb_shennan",
        600,
        420,
        "深南电路",
        "📟",
        "ABF封装基板，英伟达GPU封装核心基板",
        "core",
        "002916",
        "A股",
        ["002916"],
        "PCB制造",
    ),
    (
        "pcb_shenghong",
        900,
        420,
        "胜宏科技",
        "📟",
        "HDI/FPC印制电路板",
        "core",
        "300476",
        "A股",
        ["300476"],
        "PCB制造",
    ),
    (
        "pcb_pengding",
        1200,
        420,
        "鹏鼎控股",
        "📟",
        "FPC软板/AI终端PCB，苹果供应链",
        "core",
        "002938",
        "A股",
        ["002938"],
        "PCB制造",
    ),
    (
        "assy_fuxin",
        400,
        630,
        "工业富联",
        "🖥",
        "服务器/AI服务器PCBA组装",
        "downstream",
        "601138",
        "A股",
        ["601138"],
        "组装测试",
    ),
    (
        "assy_luxshare",
        800,
        630,
        "立讯精密",
        "🔌",
        "连接器/PCBA组装，AI服务器",
        "downstream",
        "002475",
        "A股",
        ["002475"],
        "组装测试",
    ),
    (
        "nvidia_pcb",
        400,
        840,
        "英伟达",
        "🔲",
        "AI算力服务器PCB最大需求方",
        "application",
        "NVDA",
        "US",
        [],
        "终端客户",
    ),
    (
        "huawei_pcb",
        900,
        840,
        "华为",
        "📡",
        "通信设备/昇腾服务器PCB需求",
        "application",
        "",
        "",
        [],
        "终端客户",
    ),
]:
    upsert_node(
        dict(
            industry_id="pcb",
            node_id=nid,
            x=x,
            y=y,
            label=label,
            icon=icon,
            desc=desc,
            layer=layer,
            ticker=ticker,
            market=market,
            stocks=json.dumps(stocks),
            group_name=group,
            updated_at=NOW,
        )
    )

for eid, src, tgt, lbl in [
    ("e-pcb-gf-sy", "glass_fiber", "ccl_shengyi", "玻纤布"),
    ("e-pcb-si-sy", "silica", "ccl_shengyi", "低介电填料"),
    ("e-pcb-res-hz", "resin", "ccl_huazheng", "树脂"),
    ("e-pcb-res-ny", "resin", "ccl_nanya", "树脂"),
    ("e-pcb-cu-sy", "copper_foil", "ccl_shengyi", "铜箔"),
    ("e-pcb-drill-hd", "drill_bit", "pcb_hudian", "钻孔耗材"),
    ("e-pcb-drill-sn", "drill_bit", "pcb_shennan", "钻孔耗材"),
    ("e-pcb-sy-hd", "ccl_shengyi", "pcb_hudian", "覆铜板"),
    ("e-pcb-sy-sn", "ccl_shengyi", "pcb_shennan", "覆铜板"),
    ("e-pcb-hz-sh", "ccl_huazheng", "pcb_shenghong", "覆铜板"),
    ("e-pcb-ny-pd", "ccl_nanya", "pcb_pengding", "覆铜板"),
    ("e-pcb-hd-fx", "pcb_hudian", "assy_fuxin", "服务器主板"),
    ("e-pcb-sn-fx", "pcb_shennan", "assy_fuxin", "ABF基板"),
    ("e-pcb-pd-ls", "pcb_pengding", "assy_luxshare", "FPC软板"),
    ("e-pcb-fx-nv", "assy_fuxin", "nvidia_pcb", "服务器交付"),
    ("e-pcb-ls-nv", "assy_luxshare", "nvidia_pcb", "连接器"),
    ("e-pcb-fx-hw", "assy_fuxin", "huawei_pcb", "供货"),
]:
    upsert_edge(
        dict(
            industry_id="pcb",
            edge_id=eid,
            source=src,
            target=tgt,
            layer="",
            label=lbl,
            updated_at=NOW,
        )
    )

# ---------------------------------------------------------------------------
# 3. mlcc
# ---------------------------------------------------------------------------
MLCC_STOCKS = [
    ("000636", "风华高科", "A股"),
    ("300408", "三环集团", "A股"),
    ("603585", "苏州固锝", "A股"),
    ("300285", "国瓷材料", "A股"),
    ("002601", "龙佰集团", "A股"),
    ("601899", "紫金矿业", "A股"),
    ("000878", "云南铜业", "A股"),
    ("002138", "顺络电子", "A股"),
    ("002859", "洁美科技", "A股"),
    ("601138", "工业富联", "A股"),
    ("002475", "立讯精密", "A股"),
    ("688686", "奥海科技", "A股"),
    ("002594", "广和通", "A股"),
]
for code, name, mkt in MLCC_STOCKS:
    upsert_stock(code, name, mkt, ["mlcc"])

upsert_list(
    dict(
        industry_id="mlcc",
        name="MLCC（积层陶瓷电容器）",
        sort_order=3,
        description="以英伟达为核心的被动元件产业企业关系图谱",
        icon="⚡",
        company_count=len(MLCC_STOCKS),
        last_analyzed="2026-06-27",
        representatives=json.dumps(["风华高科", "三环集团", "国瓷材料", "顺络电子"]),
        updated_at=NOW,
    )
)
upsert_meta(
    dict(
        industry_id="mlcc",
        sort_order=3,
        title="MLCC 企业供应链",
        subtitle="以英伟达为核心的被动元件产业企业关系图谱",
        layer_labels=json.dumps(
            [
                "L0 材料企业",
                "L1 关键部件企业",
                "L2 核心器件企业",
                "L3 组装/分销企业",
                "L4 终端客户",
            ]
        ),
        updated_at=NOW,
    )
)
for nid, x, y, label, icon, desc, layer, ticker, market, stocks, group in [
    (
        "barium",
        200,
        0,
        "国瓷材料",
        "⚗️",
        "钛酸钡粉/MLCC核心介质材料",
        "upstream",
        "300285",
        "A股",
        ["300285"],
        "介质材料",
    ),
    (
        "nickel",
        600,
        0,
        "龙佰集团",
        "🔶",
        "镍粉/内电极浆料原料",
        "upstream",
        "002601",
        "A股",
        ["002601"],
        "介质材料",
    ),
    (
        "copper_m",
        1000,
        0,
        "云南铜业",
        "🔶",
        "铜箔/端电极原料",
        "upstream",
        "000878",
        "A股",
        ["000878"],
        "介质材料",
    ),
    (
        "tape",
        1400,
        0,
        "洁美科技",
        "📦",
        "MLCC承载带/包装材料",
        "upstream",
        "002859",
        "A股",
        ["002859"],
        "介质材料",
    ),
    (
        "murata",
        150,
        210,
        "村田制作所",
        "🇯🇵",
        "MLCC全球龙头，AI服务器大客户",
        "core",
        "6981.T",
        "外资",
        [],
        "MLCC制造",
    ),
    (
        "tdk",
        450,
        210,
        "TDK",
        "🇯🇵",
        "MLCC/电感被动元件",
        "core",
        "6762.T",
        "外资",
        [],
        "MLCC制造",
    ),
    (
        "fenghua",
        750,
        210,
        "风华高科",
        "⚡",
        "国内MLCC龙头，替代村田",
        "core",
        "000636",
        "A股",
        ["000636"],
        "MLCC制造",
    ),
    (
        "sanhuan",
        1050,
        210,
        "三环集团",
        "⚡",
        "MLCC/陶瓷基板，AI服务器配套",
        "core",
        "300408",
        "A股",
        ["300408"],
        "MLCC制造",
    ),
    (
        "sugu",
        1350,
        210,
        "苏州固锝",
        "⚡",
        "二极管/电容，消费电子被动元件",
        "core",
        "603585",
        "A股",
        ["603585"],
        "MLCC制造",
    ),
    (
        "shunluo",
        1650,
        210,
        "顺络电子",
        "🔋",
        "叠层电感/MLCC，AI服务器配套",
        "core",
        "002138",
        "A股",
        ["002138"],
        "MLCC制造",
    ),
    (
        "assy_fw",
        400,
        420,
        "工业富联",
        "🖥",
        "AI服务器PCBA组装，MLCC大客户",
        "downstream",
        "601138",
        "A股",
        ["601138"],
        "组装分销",
    ),
    (
        "assy_ls",
        900,
        420,
        "立讯精密",
        "🔌",
        "连接器/PCBA，被动元件集成商",
        "downstream",
        "002475",
        "A股",
        ["002475"],
        "组装分销",
    ),
    (
        "nvidia_ml",
        400,
        630,
        "英伟达",
        "🔲",
        "AI服务器MLCC最大需求方",
        "application",
        "NVDA",
        "US",
        [],
        "终端客户",
    ),
    (
        "huawei_ml",
        900,
        630,
        "华为",
        "📡",
        "昇腾服务器/通信设备MLCC需求",
        "application",
        "",
        "",
        [],
        "终端客户",
    ),
]:
    upsert_node(
        dict(
            industry_id="mlcc",
            node_id=nid,
            x=x,
            y=y,
            label=label,
            icon=icon,
            desc=desc,
            layer=layer,
            ticker=ticker,
            market=market,
            stocks=json.dumps(stocks),
            group_name=group,
            updated_at=NOW,
        )
    )

for eid, src, tgt, lbl in [
    ("e-mlcc-ba-mu", "barium", "murata", "钛酸钡"),
    ("e-mlcc-ba-fh", "barium", "fenghua", "钛酸钡"),
    ("e-mlcc-ni-mu", "nickel", "murata", "镍浆料"),
    ("e-mlcc-ni-tdk", "nickel", "tdk", "镍浆料"),
    ("e-mlcc-cu-sh", "copper_m", "sanhuan", "铜电极"),
    ("e-mlcc-tp-su", "tape", "sugu", "承载带"),
    ("e-mlcc-mu-fw", "murata", "assy_fw", "供货"),
    ("e-mlcc-fh-fw", "fenghua", "assy_fw", "供货"),
    ("e-mlcc-sh-fw", "sanhuan", "assy_fw", "供货"),
    ("e-mlcc-sl-ls", "shunluo", "assy_ls", "电感"),
    ("e-mlcc-fw-nv", "assy_fw", "nvidia_ml", "交付"),
    ("e-mlcc-ls-nv", "assy_ls", "nvidia_ml", "连接器"),
    ("e-mlcc-fw-hw", "assy_fw", "huawei_ml", "供货"),
]:
    upsert_edge(
        dict(
            industry_id="mlcc",
            edge_id=eid,
            source=src,
            target=tgt,
            layer="",
            label=lbl,
            updated_at=NOW,
        )
    )

# ---------------------------------------------------------------------------
# 4. memory
# ---------------------------------------------------------------------------
MEMORY_STOCKS = [
    ("600206", "有研新材", "A股"),
    ("300666", "江丰电子", "A股"),
    ("002409", "雅克科技", "A股"),
    ("688268", "华特气体", "A股"),
    ("688126", "沪硅产业", "A股"),
    ("688300", "联瑞新材", "A股"),
    ("688019", "安集科技", "A股"),
    ("300054", "鼎龙股份", "A股"),
    ("603986", "兆易创新", "A股"),
    ("688008", "澜起科技", "A股"),
    ("688525", "佰维存储", "A股"),
    ("301308", "江波龙", "A股"),
    ("300475", "香农芯创", "A股"),
    ("688627", "精智达", "A股"),
    ("688361", "纳芯微", "A股"),
    ("601138", "工业富联", "A股"),
    ("000977", "浪潮信息", "A股"),
]
for code, name, mkt in MEMORY_STOCKS:
    upsert_stock(code, name, mkt, ["memory"])

upsert_list(
    dict(
        industry_id="memory",
        name="存储芯片（HBM/DRAM/NAND）",
        sort_order=4,
        description="以英伟达HBM需求为核心的存储芯片产业企业关系图谱",
        icon="💾",
        company_count=len(MEMORY_STOCKS),
        last_analyzed="2026-06-27",
        representatives=json.dumps(["澜起科技", "兆易创新", "佰维存储", "沪硅产业"]),
        updated_at=NOW,
    )
)
upsert_meta(
    dict(
        industry_id="memory",
        sort_order=4,
        title="存储芯片企业供应链",
        subtitle="以英伟达HBM需求为核心的存储芯片产业企业关系图谱",
        layer_labels=json.dumps(
            [
                "L0 原材料企业",
                "L1 关键材料企业",
                "L2 核心制造企业",
                "L3 封测/模组/设备",
                "L4 终端客户",
            ]
        ),
        updated_at=NOW,
    )
)
for nid, x, y, label, icon, desc, layer, ticker, market, stocks, group in [
    # L0 原材料
    (
        "mem_youyan",
        200,
        0,
        "有研新材",
        "⚗️",
        "半导体靶材/硅材料",
        "upstream",
        "600206",
        "A股",
        ["600206"],
        "原材料",
    ),
    (
        "mem_jiangfeng",
        550,
        0,
        "江丰电子",
        "⚗️",
        "超高纯溅射靶材",
        "upstream",
        "300666",
        "A股",
        ["300666"],
        "原材料",
    ),
    (
        "mem_yake",
        900,
        0,
        "雅克科技",
        "⚗️",
        "半导体前驱体/特种气体",
        "upstream",
        "002409",
        "A股",
        ["002409"],
        "原材料",
    ),
    (
        "mem_huate",
        1250,
        0,
        "华特气体",
        "🧪",
        "高纯特种气体",
        "upstream",
        "688268",
        "A股",
        ["688268"],
        "原材料",
    ),
    (
        "mem_husi",
        1600,
        0,
        "沪硅产业",
        "⚗️",
        "300mm大硅片",
        "upstream",
        "688126",
        "A股",
        ["688126"],
        "原材料",
    ),
    # L1 关键材料
    (
        "mem_lianrui",
        200,
        210,
        "联瑞新材",
        "🔬",
        "电子级球形硅微粉",
        "upstream",
        "688300",
        "A股",
        ["688300"],
        "关键材料",
    ),
    (
        "mem_anji",
        550,
        210,
        "安集科技",
        "🧪",
        "CMP抛光液/光刻胶",
        "upstream",
        "688019",
        "A股",
        ["688019"],
        "关键材料",
    ),
    (
        "mem_dinglong",
        900,
        210,
        "鼎龙股份",
        "🧪",
        "CMP抛光垫/光刻胶底层膜",
        "upstream",
        "300054",
        "A股",
        ["300054"],
        "关键材料",
    ),
    # L2 核心制造
    (
        "mem_skhynix",
        200,
        420,
        "SK海力士",
        "💾",
        "HBM全球龙头，H100/H200配套",
        "core",
        "000660",
        "KR",
        [],
        "存储制造",
    ),
    (
        "mem_samsung",
        600,
        420,
        "三星",
        "💾",
        "DRAM/NAND/HBM全球第一",
        "core",
        "005930",
        "KR",
        [],
        "存储制造",
    ),
    (
        "mem_micron",
        1000,
        420,
        "美光",
        "💾",
        "DRAM/NAND/HBM3E",
        "core",
        "MU",
        "US",
        [],
        "存储制造",
    ),
    (
        "mem_changxin",
        1400,
        420,
        "长鑫存储",
        "💾",
        "国内DRAM",
        "core",
        "",
        "",
        [],
        "存储制造",
    ),
    # L3 封测/模组/设备
    (
        "mem_lanjie",
        200,
        630,
        "澜起科技",
        "🔬",
        "内存接口芯片RCD/MR",
        "downstream",
        "688008",
        "A股",
        ["688008"],
        "封测/模组",
    ),
    (
        "mem_zhaoyi",
        500,
        630,
        "兆易创新",
        "💾",
        "NOR Flash/DRAM",
        "downstream",
        "603986",
        "A股",
        ["603986"],
        "封测/模组",
    ),
    (
        "mem_baiwei",
        800,
        630,
        "佰维存储",
        "💾",
        "存储模组/固态硬盘",
        "downstream",
        "688525",
        "A股",
        ["688525"],
        "封测/模组",
    ),
    (
        "mem_jiangbo",
        1100,
        630,
        "江波龙",
        "💾",
        "存储模组/嵌入式存储",
        "downstream",
        "301308",
        "A股",
        ["301308"],
        "封测/模组",
    ),
    (
        "mem_xiangna",
        1400,
        630,
        "香农芯创",
        "💾",
        "存储芯片分销/回收",
        "downstream",
        "300475",
        "A股",
        ["300475"],
        "封测/模组",
    ),
    (
        "mem_jingzhi",
        350,
        840,
        "精智达",
        "🔧",
        "存储测试设备",
        "application",
        "688627",
        "A股",
        ["688627"],
        "终端客户",
    ),
    (
        "mem_naxin",
        700,
        840,
        "纳芯微",
        "🔬",
        "存储接口/信号链芯片",
        "application",
        "688361",
        "A股",
        ["688361"],
        "终端客户",
    ),
    (
        "mem_fuxin",
        1050,
        840,
        "工业富联",
        "🖥",
        "AI服务器内存模组集成",
        "application",
        "601138",
        "A股",
        ["601138"],
        "终端客户",
    ),
    (
        "mem_langchao",
        1400,
        840,
        "浪潮信息",
        "🖥",
        "AI服务器HBM/DDR5",
        "application",
        "000977",
        "A股",
        ["000977"],
        "终端客户",
    ),
]:
    upsert_node(
        dict(
            industry_id="memory",
            node_id=nid,
            x=x,
            y=y,
            label=label,
            icon=icon,
            desc=desc,
            layer=layer,
            ticker=ticker,
            market=market,
            stocks=json.dumps(stocks),
            group_name=group,
            updated_at=NOW,
        )
    )

for eid, src, tgt, lbl in [
    ("e-mem-yy-sk", "mem_youyan", "mem_skhynix", "靶材"),
    ("e-mem-jf-sk", "mem_jiangfeng", "mem_skhynix", "靶材"),
    ("e-mem-yy-sa", "mem_youyan", "mem_samsung", "靶材"),
    ("e-mem-yk-sk", "mem_yake", "mem_skhynix", "前驱体"),
    ("e-mem-ht-cx", "mem_huate", "mem_changxin", "特种气体"),
    ("e-mem-hs-sa", "mem_husi", "mem_samsung", "大硅片"),
    ("e-mem-hs-cx", "mem_husi", "mem_changxin", "大硅片"),
    ("e-mem-lr-sk", "mem_lianrui", "mem_skhynix", "封装材料"),
    ("e-mem-aj-sk", "mem_anji", "mem_skhynix", "抛光液"),
    ("e-mem-aj-sa", "mem_anji", "mem_samsung", "抛光液"),
    ("e-mem-dl-mi", "mem_dinglong", "mem_micron", "抛光垫"),
    ("e-mem-sk-lj", "mem_skhynix", "mem_lanjie", "HBM芯片"),
    ("e-mem-sa-lj", "mem_samsung", "mem_lanjie", "DRAM"),
    ("e-mem-mi-zy", "mem_micron", "mem_zhaoyi", "NAND"),
    ("e-mem-sa-bw", "mem_samsung", "mem_baiwei", "颗粒"),
    ("e-mem-cx-jb", "mem_changxin", "mem_jiangbo", "DRAM颗粒"),
    ("e-mem-lj-fx", "mem_lanjie", "mem_fuxin", "接口芯片"),
    ("e-mem-bw-fx", "mem_baiwei", "mem_fuxin", "模组"),
    ("e-mem-jb-lc", "mem_jiangbo", "mem_langchao", "模组"),
    ("e-mem-xn-lc", "mem_xiangna", "mem_langchao", "存储芯片"),
    ("e-mem-jz-sk", "mem_jingzhi", "mem_skhynix", "测试设备"),
    ("e-mem-nx-lj", "mem_naxin", "mem_lanjie", "信号链"),
]:
    upsert_edge(
        dict(
            industry_id="memory",
            edge_id=eid,
            source=src,
            target=tgt,
            layer="",
            label=lbl,
            updated_at=NOW,
        )
    )

# ---------------------------------------------------------------------------
# 5. optics
# ---------------------------------------------------------------------------
OPTICS_STOCKS = [
    ("002281", "光迅科技", "A股"),
    ("688498", "源杰科技", "A股"),
    ("688048", "长光华芯", "A股"),
    ("688313", "仕佳光子", "A股"),
    ("600703", "三安光电", "A股"),
    ("300394", "天孚通信", "A股"),
    ("300620", "光库科技", "A股"),
    ("300570", "太辰光", "A股"),
    ("300548", "博创科技", "A股"),
    ("300308", "中际旭创", "A股"),
    ("300502", "新易盛", "A股"),
    ("000988", "华工科技", "A股"),
    ("603083", "剑桥科技", "A股"),
]
for code, name, mkt in OPTICS_STOCKS:
    upsert_stock(code, name, mkt, ["optics"])

upsert_list(
    dict(
        industry_id="optics",
        name="光模块与CPO",
        sort_order=5,
        description="以英伟达CPO交换机为核心的光模块/共封装光学产业链图谱",
        icon="🔦",
        company_count=len(OPTICS_STOCKS),
        last_analyzed="2026-06-27",
        representatives=json.dumps(["中际旭创", "光迅科技", "新易盛", "天孚通信"]),
        updated_at=NOW,
    )
)
upsert_meta(
    dict(
        industry_id="optics",
        sort_order=5,
        title="光模块与CPO供应链",
        subtitle="以英伟达CPO交换机为核心的光模块/共封装光学产业链图谱",
        layer_labels=json.dumps(
            [
                "L0 光芯片/硅光材料",
                "L1 光器件/组件",
                "L2 高速光模块",
                "L3 终端客户",
            ]
        ),
        updated_at=NOW,
    )
)
for nid, x, y, label, icon, desc, layer, ticker, market, stocks, group in [
    (
        "opt_coherent",
        200,
        0,
        "Coherent",
        "💡",
        "激光芯片/EML龙头",
        "upstream",
        "COHR",
        "US",
        [],
        "光芯片",
    ),
    (
        "opt_lumentum",
        500,
        0,
        "Lumentum",
        "💡",
        "VCSEL/DFB激光芯片",
        "upstream",
        "LITE",
        "US",
        [],
        "光芯片",
    ),
    (
        "opt_yuanjie",
        800,
        0,
        "源杰科技",
        "💡",
        "DFB/EML激光芯片",
        "upstream",
        "688498",
        "A股",
        ["688498"],
        "光芯片",
    ),
    (
        "opt_changguang",
        1100,
        0,
        "长光华芯",
        "💡",
        "高功率激光芯片",
        "upstream",
        "688048",
        "A股",
        ["688048"],
        "光芯片",
    ),
    (
        "opt_shijia",
        1400,
        0,
        "仕佳光子",
        "💡",
        "PLC分路器/光芯片",
        "upstream",
        "688313",
        "A股",
        ["688313"],
        "光芯片",
    ),
    (
        "opt_sanan",
        1700,
        0,
        "三安光电",
        "💡",
        "砷化镓/氮化镓激光外延",
        "upstream",
        "600703",
        "A股",
        ["600703"],
        "光芯片",
    ),
    (
        "opt_accelink",
        200,
        210,
        "光迅科技",
        "🔦",
        "国内光器件龙头，波分复用器",
        "core",
        "002281",
        "A股",
        ["002281"],
        "光器件",
    ),
    (
        "opt_tianfu",
        500,
        210,
        "天孚通信",
        "🔦",
        "光纤连接器/无源器件",
        "core",
        "300394",
        "A股",
        ["300394"],
        "光器件",
    ),
    (
        "opt_guangku",
        800,
        210,
        "光库科技",
        "🔦",
        "铌酸锂调制器/光隔离器",
        "core",
        "300620",
        "A股",
        ["300620"],
        "光器件",
    ),
    (
        "opt_taichen",
        1100,
        210,
        "太辰光",
        "🔦",
        "光纤连接器/适配器",
        "core",
        "300570",
        "A股",
        ["300570"],
        "光器件",
    ),
    (
        "opt_innolight",
        200,
        420,
        "中际旭创",
        "🔦",
        "800G/1.6T光模块龙头",
        "downstream",
        "300308",
        "A股",
        ["300308"],
        "高速光模块",
    ),
    (
        "opt_eoptolink",
        500,
        420,
        "新易盛",
        "🔦",
        "400G/800G数通光模块",
        "downstream",
        "300502",
        "A股",
        ["300502"],
        "高速光模块",
    ),
    (
        "opt_bochuang",
        800,
        420,
        "博创科技",
        "🔦",
        "高速光模块/光收发器",
        "downstream",
        "300548",
        "A股",
        ["300548"],
        "高速光模块",
    ),
    (
        "opt_huagong",
        1100,
        420,
        "华工科技",
        "🔦",
        "工业激光/光通信器件",
        "downstream",
        "000988",
        "A股",
        ["000988"],
        "高速光模块",
    ),
    (
        "opt_jianqiao",
        1400,
        420,
        "剑桥科技",
        "🔦",
        "光模块/以太网交换机",
        "downstream",
        "603083",
        "A股",
        ["603083"],
        "高速光模块",
    ),
    (
        "opt_nvda",
        400,
        630,
        "英伟达",
        "🔲",
        "NVLink/CPO共封装光学需求方",
        "application",
        "NVDA",
        "US",
        [],
        "终端客户",
    ),
    (
        "opt_cisco",
        900,
        630,
        "思科",
        "🌐",
        "800G CPO交换机",
        "application",
        "CSCO",
        "US",
        [],
        "终端客户",
    ),
    (
        "opt_broadcom",
        1400,
        630,
        "博通",
        "🔲",
        "CPO交换机ASIC",
        "application",
        "AVGO",
        "US",
        [],
        "终端客户",
    ),
]:
    upsert_node(
        dict(
            industry_id="optics",
            node_id=nid,
            x=x,
            y=y,
            label=label,
            icon=icon,
            desc=desc,
            layer=layer,
            ticker=ticker,
            market=market,
            stocks=json.dumps(stocks),
            group_name=group,
            updated_at=NOW,
        )
    )

for eid, src, tgt, lbl in [
    ("e-opt-yj-acc", "opt_yuanjie", "opt_accelink", "EML芯片"),
    ("e-opt-coh-acc", "opt_coherent", "opt_accelink", "激光芯片"),
    ("e-opt-lu-inn", "opt_lumentum", "opt_innolight", "激光芯片"),
    ("e-opt-cg-eop", "opt_changguang", "opt_eoptolink", "激光芯片"),
    ("e-opt-sa-inn", "opt_sanan", "opt_innolight", "外延片"),
    ("e-opt-sj-acc", "opt_shijia", "opt_accelink", "分路器"),
    ("e-opt-acc-inn", "opt_accelink", "opt_innolight", "光器件"),
    ("e-opt-tf-inn", "opt_tianfu", "opt_innolight", "连接器"),
    ("e-opt-tf-eop", "opt_tianfu", "opt_eoptolink", "连接器"),
    ("e-opt-gk-bc", "opt_guangku", "opt_bochuang", "调制器"),
    ("e-opt-tc-bc", "opt_taichen", "opt_bochuang", "连接器"),
    ("e-opt-inn-nv", "opt_innolight", "opt_nvda", "800G光模块"),
    ("e-opt-eop-nv", "opt_eoptolink", "opt_nvda", "400G光模块"),
    ("e-opt-bc-cs", "opt_bochuang", "opt_cisco", "光模块"),
    ("e-opt-hg-cs", "opt_huagong", "opt_cisco", "光器件"),
    ("e-opt-jq-br", "opt_jianqiao", "opt_broadcom", "光模块"),
]:
    upsert_edge(
        dict(
            industry_id="optics",
            edge_id=eid,
            source=src,
            target=tgt,
            layer="",
            label=lbl,
            updated_at=NOW,
        )
    )

# ---------------------------------------------------------------------------
# 6. fiber
# ---------------------------------------------------------------------------
FIBER_STOCKS = [
    ("300395", "菲利华", "A股"),
    ("688268", "华特气体", "A股"),
    ("002064", "华峰超纤", "A股"),
    ("601869", "长飞光纤", "A股"),
    ("600487", "亨通光电", "A股"),
    ("600522", "中天科技", "A股"),
    ("600498", "烽火通信", "A股"),
]
for code, name, mkt in FIBER_STOCKS:
    upsert_stock(code, name, mkt, ["fiber"])

upsert_list(
    dict(
        industry_id="fiber",
        name="光纤光缆",
        sort_order=6,
        description="从光纤预制棒到光缆的全产业链图谱（AI数据中心+5G/6G驱动）",
        icon="🌀",
        company_count=len(FIBER_STOCKS),
        last_analyzed="2026-06-27",
        representatives=json.dumps(["亨通光电", "长飞光纤", "中天科技", "烽火通信"]),
        updated_at=NOW,
    )
)
upsert_meta(
    dict(
        industry_id="fiber",
        sort_order=6,
        title="光纤光缆供应链",
        subtitle="从光纤预制棒到光缆的全产业链图谱（AI数据中心+5G/6G驱动）",
        layer_labels=json.dumps(
            [
                "L0 原材料",
                "L1 光纤预制棒",
                "L2 光纤/光缆制造",
                "L3 终端客户",
            ]
        ),
        updated_at=NOW,
    )
)
for nid, x, y, label, icon, desc, layer, ticker, market, stocks, group in [
    (
        "fib_sio2",
        200,
        0,
        "SiO₂原料",
        "⚗️",
        "光纤原材料四氯化硅",
        "upstream",
        "",
        "",
        [],
        "原材料",
    ),
    (
        "fib_filihua",
        600,
        0,
        "菲利华",
        "🔬",
        "高纯石英管/石英玻璃",
        "upstream",
        "300395",
        "A股",
        ["300395"],
        "原材料",
    ),
    (
        "fib_huate",
        1000,
        0,
        "华特气体",
        "🧪",
        "光纤拉丝保护气体",
        "upstream",
        "688268",
        "A股",
        ["688268"],
        "原材料",
    ),
    (
        "fib_huafeng",
        1400,
        0,
        "华峰超纤",
        "🧵",
        "光缆包覆材料/超纤材料",
        "upstream",
        "002064",
        "A股",
        ["002064"],
        "原材料",
    ),
    (
        "fib_heraeus",
        1700,
        0,
        "贺利氏",
        "🔬",
        "高纯石英管（外资）",
        "upstream",
        "",
        "",
        [],
        "原材料",
    ),
    (
        "fib_changfei",
        300,
        210,
        "长飞光纤",
        "🌀",
        "预制棒+光纤全产业链龙头",
        "core",
        "601869",
        "A股",
        ["601869"],
        "光纤预制棒",
    ),
    (
        "fib_corning",
        800,
        210,
        "康宁",
        "🌀",
        "光纤全球龙头（外资）",
        "core",
        "GLW",
        "US",
        [],
        "光纤预制棒",
    ),
    (
        "fib_prysmian",
        1300,
        210,
        "普睿斯曼",
        "🌀",
        "全球光缆巨头（外资）",
        "core",
        "",
        "",
        [],
        "光纤预制棒",
    ),
    (
        "fib_hengtong",
        300,
        420,
        "亨通光电",
        "🌀",
        "光纤光缆+海底光缆龙头",
        "downstream",
        "600487",
        "A股",
        ["600487"],
        "光纤光缆制造",
    ),
    (
        "fib_zhongtian",
        700,
        420,
        "中天科技",
        "🌀",
        "光缆+海缆+电力电缆",
        "downstream",
        "600522",
        "A股",
        ["600522"],
        "光纤光缆制造",
    ),
    (
        "fib_fenghuo",
        1100,
        420,
        "烽火通信",
        "📡",
        "光纤光缆+光网络设备",
        "downstream",
        "600498",
        "A股",
        ["600498"],
        "光纤光缆制造",
    ),
    (
        "fib_telecom",
        400,
        630,
        "三大运营商",
        "📡",
        "5G/6G光纤采购主体",
        "application",
        "",
        "",
        [],
        "终端客户",
    ),
    (
        "fib_idc_end",
        900,
        630,
        "AI数据中心",
        "🏢",
        "园区内短距光纤互联需求",
        "application",
        "",
        "",
        [],
        "终端客户",
    ),
    (
        "fib_huawei",
        1400,
        630,
        "华为",
        "📡",
        "光网络设备采购光纤",
        "application",
        "",
        "",
        [],
        "终端客户",
    ),
]:
    upsert_node(
        dict(
            industry_id="fiber",
            node_id=nid,
            x=x,
            y=y,
            label=label,
            icon=icon,
            desc=desc,
            layer=layer,
            ticker=ticker,
            market=market,
            stocks=json.dumps(stocks),
            group_name=group,
            updated_at=NOW,
        )
    )

for eid, src, tgt, lbl in [
    ("e-fib-sio-cf", "fib_sio2", "fib_changfei", "四氯化硅"),
    ("e-fib-fh-cf", "fib_filihua", "fib_changfei", "石英管"),
    ("e-fib-fh-cor", "fib_filihua", "fib_corning", "石英管"),
    ("e-fib-ht-ht2", "fib_huate", "fib_hengtong", "保护气体"),
    ("e-fib-hf-zt", "fib_huafeng", "fib_zhongtian", "护套材料"),
    ("e-fib-cf-ht", "fib_changfei", "fib_hengtong", "光纤"),
    ("e-fib-cf-zt", "fib_changfei", "fib_zhongtian", "光纤"),
    ("e-fib-cor-fh2", "fib_corning", "fib_fenghuo", "光纤"),
    ("e-fib-pr-zt", "fib_prysmian", "fib_zhongtian", "技术合作"),
    ("e-fib-ht-tel", "fib_hengtong", "fib_telecom", "光缆"),
    ("e-fib-ht-idc", "fib_hengtong", "fib_idc_end", "数据中心光缆"),
    ("e-fib-zt-tel", "fib_zhongtian", "fib_telecom", "光缆"),
    ("e-fib-fh2-hw", "fib_fenghuo", "fib_huawei", "光网设备"),
]:
    upsert_edge(
        dict(
            industry_id="fiber",
            edge_id=eid,
            source=src,
            target=tgt,
            layer="",
            label=lbl,
            updated_at=NOW,
        )
    )

# ---------------------------------------------------------------------------
# 7. liquidcool
# ---------------------------------------------------------------------------
LIQUIDCOOL_STOCKS = [
    ("300547", "朗升科技", "A股"),
    ("601992", "金隅集团", "A股"),
    ("605288", "凯迪股份", "A股"),
    ("300602", "飞荣达", "A股"),
    ("301018", "申菱环境", "A股"),
    ("300499", "高澜股份", "A股"),
    ("002837", "英维克", "A股"),
    ("688861", "彼迪科技", "A股"),
    ("300249", "依米康", "A股"),
    ("601138", "工业富联", "A股"),
]
for code, name, mkt in LIQUIDCOOL_STOCKS:
    upsert_stock(code, name, mkt, ["liquidcool"])

upsert_list(
    dict(
        industry_id="liquidcool",
        name="液冷散热",
        sort_order=7,
        description="AI芯片功耗突破1.2kW驱动液冷从可选变必选的产业链图谱",
        icon="❄️",
        company_count=len(LIQUIDCOOL_STOCKS),
        last_analyzed="2026-06-27",
        representatives=json.dumps(["英维克", "申菱环境", "高澜股份", "飞荣达"]),
        updated_at=NOW,
    )
)
upsert_meta(
    dict(
        industry_id="liquidcool",
        sort_order=7,
        title="液冷散热供应链",
        subtitle="AI芯片功耗突破1.2kW驱动液冷从可选变必选的产业链图谱",
        layer_labels=json.dumps(
            [
                "L0 液冷材料/管路",
                "L1 冷板/CDU组件",
                "L2 液冷系统集成",
                "L3 终端交付",
            ]
        ),
        updated_at=NOW,
    )
)
for nid, x, y, label, icon, desc, layer, ticker, market, stocks, group in [
    (
        "lc_coolant",
        200,
        0,
        "冷却液",
        "💧",
        "乙二醇基绝缘冷却液",
        "upstream",
        "",
        "",
        [],
        "液冷材料",
    ),
    (
        "lc_langsheng",
        550,
        0,
        "朗升科技",
        "🔧",
        "液冷管路/快接接头",
        "upstream",
        "300547",
        "A股",
        ["300547"],
        "液冷材料",
    ),
    (
        "lc_feirong",
        900,
        0,
        "飞荣达",
        "🔧",
        "热管理/散热片/液冷板",
        "upstream",
        "300602",
        "A股",
        ["300602"],
        "液冷材料",
    ),
    (
        "lc_bidi",
        1250,
        0,
        "彼迪科技",
        "🔧",
        "精密热管理部件",
        "upstream",
        "688861",
        "A股",
        ["688861"],
        "液冷材料",
    ),
    (
        "lc_vertiv",
        1600,
        0,
        "维谛技术",
        "❄️",
        "CDU/液冷基础设施（外资）",
        "upstream",
        "VRT",
        "US",
        [],
        "液冷材料",
    ),
    (
        "lc_gaolan",
        200,
        210,
        "高澜股份",
        "❄️",
        "轨道交通/数据中心液冷",
        "core",
        "300499",
        "A股",
        ["300499"],
        "冷板/CDU",
    ),
    (
        "lc_shenling",
        550,
        210,
        "申菱环境",
        "❄️",
        "液冷空调/CDU/背板液冷",
        "core",
        "301018",
        "A股",
        ["301018"],
        "冷板/CDU",
    ),
    (
        "lc_yimikang",
        900,
        210,
        "依米康",
        "❄️",
        "浸没式液冷/数据中心精密空调",
        "core",
        "300249",
        "A股",
        ["300249"],
        "冷板/CDU",
    ),
    (
        "lc_kaidi",
        1250,
        210,
        "凯迪股份",
        "❄️",
        "散热器/铝散热模组",
        "core",
        "605288",
        "A股",
        ["605288"],
        "冷板/CDU",
    ),
    (
        "lc_yingweike",
        200,
        420,
        "英维克",
        "❄️",
        "液冷机柜/冷板液冷系统集成龙头",
        "downstream",
        "002837",
        "A股",
        ["002837"],
        "液冷系统",
    ),
    (
        "lc_jinyv",
        550,
        420,
        "金隅集团",
        "🏗",
        "IDC基础建设/机房土建",
        "downstream",
        "601992",
        "A股",
        ["601992"],
        "液冷系统",
    ),
    (
        "lc_fuxin",
        900,
        420,
        "工业富联",
        "🖥",
        "AI服务器整机液冷集成交付",
        "downstream",
        "601138",
        "A股",
        ["601138"],
        "液冷系统",
    ),
    (
        "lc_nvda",
        400,
        630,
        "英伟达GB200",
        "🔲",
        "GB200/GB300机柜液冷需求方",
        "application",
        "NVDA",
        "US",
        [],
        "终端交付",
    ),
    (
        "lc_idc",
        1000,
        630,
        "AI数据中心",
        "🏢",
        "整柜/浸没液冷部署场景",
        "application",
        "",
        "",
        [],
        "终端交付",
    ),
]:
    upsert_node(
        dict(
            industry_id="liquidcool",
            node_id=nid,
            x=x,
            y=y,
            label=label,
            icon=icon,
            desc=desc,
            layer=layer,
            ticker=ticker,
            market=market,
            stocks=json.dumps(stocks),
            group_name=group,
            updated_at=NOW,
        )
    )

for eid, src, tgt, lbl in [
    ("e-liq-cl-gl", "lc_coolant", "lc_gaolan", "冷却液"),
    ("e-liq-ls-sl", "lc_langsheng", "lc_shenling", "管路接头"),
    ("e-liq-fr-yw", "lc_feirong", "lc_yingweike", "冷板"),
    ("e-liq-bd-yk", "lc_bidi", "lc_yimikang", "热管理部件"),
    ("e-liq-vt-sl", "lc_vertiv", "lc_shenling", "CDU"),
    ("e-liq-gl-yw", "lc_gaolan", "lc_yingweike", "液冷单元"),
    ("e-liq-sl-yw", "lc_shenling", "lc_yingweike", "CDU"),
    ("e-liq-yk-fx", "lc_yimikang", "lc_fuxin", "浸没液冷"),
    ("e-liq-kd-yw", "lc_kaidi", "lc_yingweike", "散热模组"),
    ("e-liq-yw-nv", "lc_yingweike", "lc_nvda", "液冷柜"),
    ("e-liq-fx-nv", "lc_fuxin", "lc_nvda", "整机"),
    ("e-liq-jy-idc", "lc_jinyv", "lc_idc", "机房建设"),
    ("e-liq-yw-idc", "lc_yingweike", "lc_idc", "液冷系统"),
]:
    upsert_edge(
        dict(
            industry_id="liquidcool",
            edge_id=eid,
            source=src,
            target=tgt,
            layer="",
            label=lbl,
            updated_at=NOW,
        )
    )

# ---------------------------------------------------------------------------
# 8. aipower
# ---------------------------------------------------------------------------
AIPOWER_STOCKS = [
    ("600563", "法拉电子", "A股"),
    ("002245", "奥特讯", "A股"),
    ("688601", "力芯微", "A股"),
    ("603290", "斯达半导", "A股"),
    ("688396", "华润微", "A股"),
    ("600089", "特变电工", "A股"),
    ("002851", "麦格米特", "A股"),
    ("002364", "中恒电气", "A股"),
    ("002335", "科华数据", "A股"),
    ("300870", "欧陆通", "A股"),
    ("002518", "科士达", "A股"),
    ("688676", "金禄电子", "A股"),
]
for code, name, mkt in AIPOWER_STOCKS:
    upsert_stock(code, name, mkt, ["aipower"])

upsert_list(
    dict(
        industry_id="aipower",
        name="AI供配电（PSU/BBU/HVDC）",
        sort_order=8,
        description="GB200/GB300机柜供配电体系（PSU/BBU/HVDC）产业图谱",
        icon="⚡",
        company_count=len(AIPOWER_STOCKS),
        last_analyzed="2026-06-27",
        representatives=json.dumps(["麦格米特", "科华数据", "斯达半导", "特变电工"]),
        updated_at=NOW,
    )
)
upsert_meta(
    dict(
        industry_id="aipower",
        sort_order=8,
        title="AI供配电供应链",
        subtitle="GB200/GB300机柜供配电体系（PSU/BBU/HVDC）产业图谱",
        layer_labels=json.dumps(
            [
                "L0 核心原材料",
                "L1 关键电源模块",
                "L2 供配电系统集成",
                "L3 终端客户",
            ]
        ),
        updated_at=NOW,
    )
)
for nid, x, y, label, icon, desc, layer, ticker, market, stocks, group in [
    (
        "pw_fala",
        200,
        0,
        "法拉电子",
        "⚡",
        "铝电解电容/薄膜电容",
        "upstream",
        "600563",
        "A股",
        ["600563"],
        "核心原材料",
    ),
    (
        "pw_lixin",
        550,
        0,
        "力芯微",
        "⚡",
        "电源管理IC/驱动IC",
        "upstream",
        "688601",
        "A股",
        ["688601"],
        "核心原材料",
    ),
    (
        "pw_sida",
        900,
        0,
        "斯达半导",
        "⚡",
        "IGBT/SiC功率模块",
        "upstream",
        "603290",
        "A股",
        ["603290"],
        "核心原材料",
    ),
    (
        "pw_huarun",
        1250,
        0,
        "华润微",
        "⚡",
        "功率器件/MOSFET/SBD",
        "upstream",
        "688396",
        "A股",
        ["688396"],
        "核心原材料",
    ),
    (
        "pw_jinlu",
        1600,
        0,
        "金禄电子",
        "⚡",
        "高频变压器/磁性元件",
        "upstream",
        "688676",
        "A股",
        ["688676"],
        "核心原材料",
    ),
    (
        "pw_maige",
        200,
        210,
        "麦格米特",
        "🔋",
        "服务器PSU/HVDC模块",
        "core",
        "002851",
        "A股",
        ["002851"],
        "关键电源模块",
    ),
    (
        "pw_ouluton",
        550,
        210,
        "欧陆通",
        "🔋",
        "服务器PSU/电源适配器",
        "core",
        "300870",
        "A股",
        ["300870"],
        "关键电源模块",
    ),
    (
        "pw_zhongheng",
        900,
        210,
        "中恒电气",
        "🔋",
        "通信电源/BBU模块",
        "core",
        "002364",
        "A股",
        ["002364"],
        "关键电源模块",
    ),
    (
        "pw_delta",
        1250,
        210,
        "台达电子",
        "⚡",
        "PSU/UPS龙头（外资）",
        "core",
        "2308",
        "TW",
        [],
        "关键电源模块",
    ),
    (
        "pw_tebian",
        200,
        420,
        "特变电工",
        "⚡",
        "变压器/高压配电设备",
        "downstream",
        "600089",
        "A股",
        ["600089"],
        "供配电系统",
    ),
    (
        "pw_kehua",
        550,
        420,
        "科华数据",
        "⚡",
        "UPS/模块电源/HVDC系统",
        "downstream",
        "002335",
        "A股",
        ["002335"],
        "供配电系统",
    ),
    (
        "pw_keshida",
        900,
        420,
        "科士达",
        "⚡",
        "UPS/储能系统/IDC配电",
        "downstream",
        "002518",
        "A股",
        ["002518"],
        "供配电系统",
    ),
    (
        "pw_aotexun",
        1250,
        420,
        "奥特讯",
        "🔧",
        "高功率测试电源/充放电设备",
        "downstream",
        "002245",
        "A股",
        ["002245"],
        "供配电系统",
    ),
    (
        "pw_nvda",
        450,
        630,
        "英伟达GB200",
        "🔲",
        "GB200/GB300机柜供配电需求方",
        "application",
        "NVDA",
        "US",
        [],
        "终端客户",
    ),
    (
        "pw_idc",
        1050,
        630,
        "AI数据中心",
        "🏢",
        "IDC配电系统需求方",
        "application",
        "",
        "",
        [],
        "终端客户",
    ),
]:
    upsert_node(
        dict(
            industry_id="aipower",
            node_id=nid,
            x=x,
            y=y,
            label=label,
            icon=icon,
            desc=desc,
            layer=layer,
            ticker=ticker,
            market=market,
            stocks=json.dumps(stocks),
            group_name=group,
            updated_at=NOW,
        )
    )

for eid, src, tgt, lbl in [
    ("e-pw-fl-mg", "pw_fala", "pw_maige", "电容"),
    ("e-pw-fl-ol", "pw_fala", "pw_ouluton", "电容"),
    ("e-pw-lx-mg", "pw_lixin", "pw_maige", "驱动IC"),
    ("e-pw-sd-mg", "pw_sida", "pw_maige", "IGBT"),
    ("e-pw-sd-kh", "pw_sida", "pw_kehua", "功率模块"),
    ("e-pw-hr-ol", "pw_huarun", "pw_ouluton", "MOSFET"),
    ("e-pw-jl-zh", "pw_jinlu", "pw_zhongheng", "变压器"),
    ("e-pw-mg-tb", "pw_maige", "pw_tebian", "HVDC模块"),
    ("e-pw-ol-kh", "pw_ouluton", "pw_kehua", "PSU模块"),
    ("e-pw-zh-ksd", "pw_zhongheng", "pw_keshida", "BBU"),
    ("e-pw-dt-kh", "pw_delta", "pw_kehua", "参考方案"),
    ("e-pw-tb-nv", "pw_tebian", "pw_nvda", "配电系统"),
    ("e-pw-kh-nv", "pw_kehua", "pw_nvda", "HVDC/UPS"),
    ("e-pw-ksd-idc", "pw_keshida", "pw_idc", "UPS"),
    ("e-pw-at-idc", "pw_aotexun", "pw_idc", "测试电源"),
]:
    upsert_edge(
        dict(
            industry_id="aipower",
            edge_id=eid,
            source=src,
            target=tgt,
            layer="",
            label=lbl,
            updated_at=NOW,
        )
    )

# ---------------------------------------------------------------------------
# 9. coppercable
# ---------------------------------------------------------------------------
COPPERCABLE_STOCKS = [
    ("000630", "铜陵有色", "A股"),
    ("600110", "中科宇航", "A股"),
    ("002130", "沃尔核材", "A股"),
    ("300913", "兆龙互联", "A股"),
    ("603465", "瑞可达", "A股"),
    ("603659", "璞泰来", "A股"),
]
for code, name, mkt in COPPERCABLE_STOCKS:
    upsert_stock(code, name, mkt, ["coppercable"])

upsert_list(
    dict(
        industry_id="coppercable",
        name="高速铜连接（DAC/AEC）",
        sort_order=9,
        description="AI机柜内GPU-Switch短距互联铜缆（DAC/AEC）产业图谱",
        icon="🔌",
        company_count=len(COPPERCABLE_STOCKS),
        last_analyzed="2026-06-27",
        representatives=json.dumps(["兆龙互联", "瑞可达", "沃尔核材"]),
        updated_at=NOW,
    )
)
upsert_meta(
    dict(
        industry_id="coppercable",
        sort_order=9,
        title="高速铜连接供应链",
        subtitle="AI机柜内GPU-Switch短距互联铜缆（DAC/AEC）产业图谱",
        layer_labels=json.dumps(
            [
                "L0 原材料",
                "L1 线缆/连接器制造",
                "L2 高速互联模组",
                "L3 终端客户",
            ]
        ),
        updated_at=NOW,
    )
)
for nid, x, y, label, icon, desc, layer, ticker, market, stocks, group in [
    (
        "cu_copper",
        200,
        0,
        "铜陵有色",
        "🔶",
        "高纯铜杆/铜箔原料",
        "upstream",
        "000630",
        "A股",
        ["000630"],
        "原材料",
    ),
    (
        "cu_zhongke",
        600,
        0,
        "中科宇航",
        "🔶",
        "特种导体材料",
        "upstream",
        "600110",
        "A股",
        ["600110"],
        "原材料",
    ),
    (
        "cu_putal",
        1000,
        0,
        "璞泰来",
        "⚗️",
        "导电涂层/屏蔽材料",
        "upstream",
        "603659",
        "A股",
        ["603659"],
        "原材料",
    ),
    (
        "cu_amphenol",
        1400,
        0,
        "安费诺",
        "🔌",
        "高速连接器龙头（外资）",
        "upstream",
        "APH",
        "US",
        [],
        "原材料",
    ),
    (
        "cu_woer",
        200,
        210,
        "沃尔核材",
        "🔌",
        "热缩管/导线/特种线缆",
        "core",
        "002130",
        "A股",
        ["002130"],
        "线缆/连接器",
    ),
    (
        "cu_ruikeda",
        600,
        210,
        "瑞可达",
        "🔌",
        "高速线束/连接器组件",
        "core",
        "603465",
        "A股",
        ["603465"],
        "线缆/连接器",
    ),
    (
        "cu_molex",
        1000,
        210,
        "莫仕",
        "🔌",
        "高速线缆组件（外资）",
        "core",
        "",
        "",
        [],
        "线缆/连接器",
    ),
    (
        "cu_te",
        1400,
        210,
        "泰科电子",
        "🔌",
        "高速连接器TE（外资）",
        "core",
        "TEL",
        "US",
        [],
        "线缆/连接器",
    ),
    (
        "cu_zhaolong",
        400,
        420,
        "兆龙互联",
        "🔌",
        "国内DAC/AOC高速线缆龙头",
        "downstream",
        "300913",
        "A股",
        ["300913"],
        "高速互联模组",
    ),
    (
        "cu_liqtech",
        900,
        420,
        "利达光通",
        "🔌",
        "AEC有源铜缆模组",
        "downstream",
        "",
        "",
        [],
        "高速互联模组",
    ),
    (
        "cu_nvda",
        400,
        630,
        "英伟达NVL72",
        "🔲",
        "机柜内GPU-NVSwitch短距互联",
        "application",
        "NVDA",
        "US",
        [],
        "终端客户",
    ),
    (
        "cu_broadcom",
        900,
        630,
        "博通",
        "🔲",
        "交换机ASIC-DAC互联",
        "application",
        "AVGO",
        "US",
        [],
        "终端客户",
    ),
    (
        "cu_cisco",
        1400,
        630,
        "思科",
        "🌐",
        "400G以太网交换机铜缆互联",
        "application",
        "CSCO",
        "US",
        [],
        "终端客户",
    ),
]:
    upsert_node(
        dict(
            industry_id="coppercable",
            node_id=nid,
            x=x,
            y=y,
            label=label,
            icon=icon,
            desc=desc,
            layer=layer,
            ticker=ticker,
            market=market,
            stocks=json.dumps(stocks),
            group_name=group,
            updated_at=NOW,
        )
    )

for eid, src, tgt, lbl in [
    ("e-cu-cop-wo", "cu_copper", "cu_woer", "铜材"),
    ("e-cu-cop-rk", "cu_copper", "cu_ruikeda", "铜材"),
    ("e-cu-zk-zl", "cu_zhongke", "cu_zhaolong", "导体材料"),
    ("e-cu-pt-zl", "cu_putal", "cu_zhaolong", "涂层"),
    ("e-cu-am-rk", "cu_amphenol", "cu_ruikeda", "连接器"),
    ("e-cu-wo-zl", "cu_woer", "cu_zhaolong", "线缆"),
    ("e-cu-rk-zl", "cu_ruikeda", "cu_zhaolong", "组件"),
    ("e-cu-mo-lt", "cu_molex", "cu_liqtech", "AEC组件"),
    ("e-cu-te-rk", "cu_te", "cu_ruikeda", "连接器"),
    ("e-cu-zl-nv", "cu_zhaolong", "cu_nvda", "DAC铜缆"),
    ("e-cu-lt-br", "cu_liqtech", "cu_broadcom", "AEC"),
    ("e-cu-rk-cs", "cu_ruikeda", "cu_cisco", "线束"),
]:
    upsert_edge(
        dict(
            industry_id="coppercable",
            edge_id=eid,
            source=src,
            target=tgt,
            layer="",
            label=lbl,
            updated_at=NOW,
        )
    )

# ---------------------------------------------------------------------------
# 10. idc
# ---------------------------------------------------------------------------
IDC_STOCKS = [
    ("000063", "中兴通讯", "A股"),
    ("002518", "科士达", "A股"),
    ("002837", "英维克", "A股"),
    ("603912", "稳健医疗", "A股"),
    ("300442", "中新赛克", "A股"),
    ("300738", "奥飞数据", "A股"),
    ("300383", "光环新网", "A股"),
]
for code, name, mkt in IDC_STOCKS:
    upsert_stock(code, name, mkt, ["idc"])

upsert_list(
    dict(
        industry_id="idc",
        name="智算中心/IDC运营",
        sort_order=10,
        description="AI算力基础设施载体——智算中心建设与运营产业链图谱",
        icon="🏢",
        company_count=len(IDC_STOCKS),
        last_analyzed="2026-06-27",
        representatives=json.dumps(["光环新网", "奥飞数据", "中兴通讯", "科士达"]),
        updated_at=NOW,
    )
)
upsert_meta(
    dict(
        industry_id="idc",
        sort_order=10,
        title="智算中心/IDC供应链",
        subtitle="AI算力基础设施载体——智算中心建设与运营产业链图谱",
        layer_labels=json.dumps(
            [
                "L0 基础设施建设",
                "L1 机房配套设备",
                "L2 智算中心运营",
                "L3 算力服务客户",
            ]
        ),
        updated_at=NOW,
    )
)
for nid, x, y, label, icon, desc, layer, ticker, market, stocks, group in [
    (
        "idc_land",
        200,
        0,
        "土地/能源",
        "🏗",
        "IDC选址/电力资源/数据中心园区",
        "upstream",
        "",
        "",
        [],
        "基础设施",
    ),
    (
        "idc_zte",
        600,
        0,
        "中兴通讯",
        "📡",
        "网络设备/智算中心方案",
        "upstream",
        "000063",
        "A股",
        ["000063"],
        "基础设施",
    ),
    (
        "idc_huawei_nw",
        1000,
        0,
        "华为",
        "📡",
        "智算中心整体方案/昇腾集群",
        "upstream",
        "",
        "",
        [],
        "基础设施",
    ),
    (
        "idc_keshida",
        200,
        210,
        "科士达",
        "⚡",
        "UPS/精密空调/IDC配电",
        "core",
        "002518",
        "A股",
        ["002518"],
        "机房配套",
    ),
    (
        "idc_yingweike",
        550,
        210,
        "英维克",
        "❄️",
        "液冷/精密空调/机柜",
        "core",
        "002837",
        "A股",
        ["002837"],
        "机房配套",
    ),
    (
        "idc_zhonxin",
        900,
        210,
        "中新赛克",
        "🔒",
        "网络安全/流量监控设备",
        "core",
        "300442",
        "A股",
        ["300442"],
        "机房配套",
    ),
    (
        "idc_wenjian",
        1250,
        210,
        "稳健医疗",
        "🏗",
        "IDC洁净室/防静电材料",
        "core",
        "603912",
        "A股",
        ["603912"],
        "机房配套",
    ),
    (
        "idc_aofei",
        200,
        420,
        "奥飞数据",
        "🏢",
        "IDC运营/云计算/AI算力出租",
        "downstream",
        "300738",
        "A股",
        ["300738"],
        "IDC运营",
    ),
    (
        "idc_guanghuan",
        600,
        420,
        "光环新网",
        "🏢",
        "中立IDC+AWS合作/云计算",
        "downstream",
        "300383",
        "A股",
        ["300383"],
        "IDC运营",
    ),
    (
        "idc_wanguo",
        1000,
        420,
        "万国数据",
        "🏢",
        "大型IDC运营商（中立）",
        "downstream",
        "GDS",
        "US",
        [],
        "IDC运营",
    ),
    (
        "idc_ali",
        300,
        630,
        "阿里云",
        "☁️",
        "公有云AI算力平台",
        "application",
        "BABA",
        "US",
        [],
        "算力客户",
    ),
    (
        "idc_huawei_cl",
        700,
        630,
        "华为云",
        "☁️",
        "政企AI云/盘古大模型",
        "application",
        "",
        "",
        [],
        "算力客户",
    ),
    (
        "idc_baidu",
        1100,
        630,
        "百度智能云",
        "☁️",
        "文心大模型/AI算力租用",
        "application",
        "BIDU",
        "US",
        [],
        "算力客户",
    ),
]:
    upsert_node(
        dict(
            industry_id="idc",
            node_id=nid,
            x=x,
            y=y,
            label=label,
            icon=icon,
            desc=desc,
            layer=layer,
            ticker=ticker,
            market=market,
            stocks=json.dumps(stocks),
            group_name=group,
            updated_at=NOW,
        )
    )

for eid, src, tgt, lbl in [
    ("e-idc-ld-ks", "idc_land", "idc_keshida", "能源接入"),
    ("e-idc-ld-yw", "idc_land", "idc_yingweike", "机房建设"),
    ("e-idc-zte-af", "idc_zte", "idc_aofei", "网络设备"),
    ("e-idc-hw-gh", "idc_huawei_nw", "idc_guanghuan", "智算方案"),
    ("e-idc-ks-af", "idc_keshida", "idc_aofei", "UPS/配电"),
    ("e-idc-yw-af", "idc_yingweike", "idc_aofei", "液冷/精空"),
    ("e-idc-yw-gh", "idc_yingweike", "idc_guanghuan", "机柜"),
    ("e-idc-zx-wg", "idc_zhonxin", "idc_wanguo", "安全设备"),
    ("e-idc-wj-wg", "idc_wenjian", "idc_wanguo", "洁净材料"),
    ("e-idc-af-ali", "idc_aofei", "idc_ali", "算力服务"),
    ("e-idc-gh-hw2", "idc_guanghuan", "idc_huawei_cl", "算力服务"),
    ("e-idc-wg-bdu", "idc_wanguo", "idc_baidu", "算力服务"),
]:
    upsert_edge(
        dict(
            industry_id="idc",
            edge_id=eid,
            source=src,
            target=tgt,
            layer="",
            label=lbl,
            updated_at=NOW,
        )
    )

# ---------------------------------------------------------------------------
# 11. glasssub
# ---------------------------------------------------------------------------
GLASSSUB_STOCKS = [
    ("600876", "洛阳玻璃", "A股"),
    ("600707", "彩虹股份", "A股"),
    ("000012", "南玻A", "A股"),
    ("600586", "金晶科技", "A股"),
    ("605305", "中材科技", "A股"),
    ("300408", "三环集团", "A股"),
    ("002006", "精功科技", "A股"),
    ("688037", "芯源微", "A股"),
    ("601636", "旗滨集团", "A股"),
    ("002916", "深南电路", "A股"),
    ("688185", "康希通信", "A股"),
    ("000725", "京东方A", "A股"),
    ("000050", "深天马A", "A股"),
    ("002652", "蓝思科技", "A股"),
    ("002475", "立讯精密", "A股"),
    ("002241", "歌尔股份", "A股"),
    ("002129", "中环股份", "A股"),
    ("688599", "天岳先进", "A股"),
]
for code, name, mkt in GLASSSUB_STOCKS:
    upsert_stock(code, name, mkt, ["glasssub"])

upsert_list(
    dict(
        industry_id="glasssub",
        name="玻璃基板（半导体封装/面板）",
        sort_order=11,
        description="覆盖玻璃基板材料制备到半导体先进封装、面板显示的完整链路",
        icon="🔬",
        company_count=len(GLASSSUB_STOCKS),
        last_analyzed="2026-06-27",
        representatives=json.dumps(["洛阳玻璃", "彩虹股份", "南玻A", "京东方A"]),
        updated_at=NOW,
    )
)
upsert_meta(
    dict(
        industry_id="glasssub",
        sort_order=11,
        title="玻璃基板（半导体封装/面板）产业链",
        subtitle="从特种玻璃原料到半导体封装基板、显示面板的完整链路",
        layer_labels=json.dumps(
            ["上游原料/设备", "玻璃基板制造", "下游封装/面板", "终端应用"]
        ),
        updated_at=NOW,
    )
)
for nid, x, y, label, icon, desc, layer, ticker, market, stocks in [
    ("sio2_glass", 150, 0, "高纯石英", "⚗️", "玻璃基板核心原料", "upstream", "", "", []),
    (
        "luobo",
        450,
        0,
        "洛阳玻璃",
        "🔬",
        "特种玻璃/电子玻璃",
        "upstream",
        "600876",
        "A股",
        ["600876"],
    ),
    (
        "cailiao",
        750,
        0,
        "中材科技",
        "🏗",
        "玻璃纤维/特种材料",
        "upstream",
        "605305",
        "A股",
        ["605305"],
    ),
    (
        "jingong_eq",
        1050,
        0,
        "精功科技",
        "🛠",
        "玻璃制程装备",
        "upstream",
        "002006",
        "A股",
        ["002006"],
    ),
    (
        "xinyuan_eq",
        1350,
        0,
        "芯源微",
        "🛠",
        "半导体清洗设备",
        "upstream",
        "688037",
        "A股",
        ["688037"],
    ),
    (
        "corning_gl",
        1650,
        0,
        "康宁",
        "🔬",
        "OLED/封装玻璃基板",
        "upstream",
        "GLW",
        "US",
        [],
    ),
    (
        "caihong",
        200,
        210,
        "彩虹股份",
        "🎨",
        "液晶/OLED玻璃基板",
        "core",
        "600707",
        "A股",
        ["600707"],
    ),
    (
        "nanbo",
        500,
        210,
        "南玻A",
        "🔬",
        "建筑/电子玻璃",
        "core",
        "000012",
        "A股",
        ["000012"],
    ),
    (
        "jinjing",
        800,
        210,
        "金晶科技",
        "🔬",
        "特种玻璃",
        "core",
        "600586",
        "A股",
        ["600586"],
    ),
    (
        "qibin",
        1100,
        210,
        "旗滨集团",
        "🔬",
        "电子/光伏玻璃",
        "core",
        "601636",
        "A股",
        ["601636"],
    ),
    (
        "sanhuan_gs",
        1400,
        210,
        "三环集团",
        "⚡",
        "陶瓷封装/基板",
        "core",
        "300408",
        "A股",
        ["300408"],
    ),
    (
        "tianyue",
        1700,
        210,
        "天岳先进",
        "💎",
        "SiC衬底基板",
        "core",
        "688599",
        "A股",
        ["688599"],
    ),
    (
        "shennan_pkg",
        200,
        420,
        "深南电路",
        "📟",
        "高端封装基板PCB",
        "downstream",
        "002916",
        "A股",
        ["002916"],
    ),
    (
        "kangxi",
        500,
        420,
        "康希通信",
        "📡",
        "射频封装",
        "downstream",
        "688185",
        "A股",
        ["688185"],
    ),
    (
        "boe",
        800,
        420,
        "京东方A",
        "📺",
        "OLED/LCD面板",
        "downstream",
        "000725",
        "A股",
        ["000725"],
    ),
    (
        "tianma",
        1100,
        420,
        "深天马A",
        "📺",
        "中小尺寸OLED",
        "downstream",
        "000050",
        "A股",
        ["000050"],
    ),
    (
        "lens",
        1400,
        420,
        "蓝思科技",
        "📱",
        "盖板玻璃/组装",
        "downstream",
        "002652",
        "A股",
        ["002652"],
    ),
    (
        "luxshare",
        1700,
        420,
        "立讯精密",
        "🔌",
        "精密连接/封装",
        "downstream",
        "002475",
        "A股",
        ["002475"],
    ),
    ("apple", 350, 630, "苹果", "🍎", "消费电子终端", "application", "AAPL", "US", []),
    (
        "goer",
        750,
        630,
        "歌尔股份",
        "🎧",
        "VR/AR声学器件",
        "application",
        "002241",
        "A股",
        ["002241"],
    ),
    (
        "huansheng",
        1150,
        630,
        "中环股份",
        "🌞",
        "光伏硅片",
        "application",
        "002129",
        "A股",
        ["002129"],
    ),
    (
        "nvidia_pkg",
        1550,
        630,
        "英伟达",
        "🔲",
        "AI芯片先进封装需求",
        "application",
        "NVDA",
        "US",
        [],
    ),
]:
    upsert_node(
        dict(
            industry_id="glasssub",
            node_id=nid,
            x=x,
            y=y,
            label=label,
            icon=icon,
            desc=desc,
            layer=layer,
            ticker=ticker,
            market=market,
            stocks=json.dumps(stocks),
            updated_at=NOW,
        )
    )

for eid, src, tgt, lbl in [
    ("e-gs-sio-lb", "sio2_glass", "luobo", "原料"),
    ("e-gs-sio-ch", "sio2_glass", "caihong", "原料"),
    ("e-gs-cor-boe", "corning_gl", "boe", "基板"),
    ("e-gs-lb-ch", "luobo", "caihong", "原料"),
    ("e-gs-cm-jj", "cailiao", "jinjing", "材料"),
    ("e-gs-ch-boe", "caihong", "boe", "玻璃基板"),
    ("e-gs-nb-lens", "nanbo", "lens", "盖板玻璃"),
    ("e-gs-qb-boe", "qibin", "boe", "电子玻璃"),
    ("e-gs-sh-boe", "sanhuan_gs", "boe", "封装基板"),
    ("e-gs-sn-nvda", "shennan_pkg", "nvidia_pkg", "封装基板"),
    ("e-gs-ty-nvda", "tianyue", "nvidia_pkg", "SiC基板"),
    ("e-gs-boe-app", "boe", "apple", "面板"),
    ("e-gs-tm-app", "tianma", "apple", "面板"),
    ("e-gs-lens-app", "lens", "apple", "盖板"),
    ("e-gs-lux-app", "luxshare", "apple", "组装"),
    ("e-gs-goer-app", "goer", "apple", "声学"),
    ("e-gs-kx-nvda", "kangxi", "nvidia_pkg", "射频封装"),
    ("e-gs-eq-ch", "jingong_eq", "caihong", "装备"),
    ("e-gs-xm-sn", "xinyuan_eq", "shennan_pkg", "清洗设备"),
]:
    upsert_edge(
        dict(
            industry_id="glasssub",
            edge_id=eid,
            source=src,
            target=tgt,
            layer="",
            label=lbl,
            updated_at=NOW,
        )
    )

# ---------------------------------------------------------------------------
# Commit
# ---------------------------------------------------------------------------
db.commit()
db.close()

print("=== Seed complete ===")
from db import (
    SessionLocal as S2,
    IndustryList as IL,
    IndustryMeta as IM,
    IndustryNode as IN,
    IndustryEdge as IE,
    StockMeta as SM,
)

d2 = S2()
print(f"  IndustryList : {d2.query(IL).count()}")
print(f"  IndustryMeta : {d2.query(IM).count()}")
print(f"  IndustryNode : {d2.query(IN).count()}")
print(f"  IndustryEdge : {d2.query(IE).count()}")
print(f"  StockMeta    : {d2.query(SM).count()}")
d2.close()
